### ISSUE TITLE
Recipe Card Component

### ISSUE THREAD

**Issue by grantDuntugan** [cse110-fa21-group24/cse110-fa21-group24#21]
**Description**
The recipe card component with the picture of the recipe, recipe name, description. Note that the recipe card component is different for each page, so you might need to make different versions with their respective buttons (add button, learn more, delete, etc.) This issue should be finished before all other UI issues.

**Possible Solutions**
You can either create separate recipe cards for the different occurrences, or you can use the same and find a way to adaptively reveal the content (by class name or something else which can be handled in javascript later!)

**Issue Points**: 1

**Comment by ansavp** [comment]
https://user-images.githubusercontent.com/81841484/141393362-9a78cfa4-4877-4d31-85b9-976132f6fef7.mov

**Comment by ansavp** [comment]
https://user-images.githubusercontent.com/81841484/141428486-513b80d3-c797-4e7f-824d-29dc08cf10a7.mov
